git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  
gui:
  # Use delta for better diff viewing
  showFileTree: true
  showCommandLog: false
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse

os:
  # Don't open difftool, use the built-in pager instead
  editCommand: '{{- if lookPath "nvim" }}nvim{{- else if lookPath "vim" }}vim{{- else }}vi{{- end }}'
  editCommandTemplate: '{{`{{editor}}`}} {{`{{filename}}`}}'

keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'