set nocompatible
filetype off
"set backspace=indent,eol,start

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim

" Load vundle bundles
if filereadable(expand("~/.vim/vundles.vim"))
    source ~/.vim/vundles.vim
endif

filetype plugin indent on

let mapleader=','

" General config

colorscheme molokai
set guifont=Meslo\ LG\ S\ DZ\ for\ Powerline
set t_Co=256
set number                      "Line numbers are good
set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set showcmd                     "Show incomplete cmds down the bottom
set showmode                    "Show current mode down the bottom
"set gcr=a:blinkon0              "Disable cursor blink
"set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim
set ruler	                " show the cursor position all the time
set expandtab                   " expand spaces into tabs in insert mode
set shiftwidth=2
set softtabstop=2
set nowrap
set linebreak                   " wrap at convenient places
set autoindent

" display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

" allow buffers to exist in the background
set hidden

" syntax highlighting
syntax on

" no swap
set noswapfile
set nobackup
set nowb

"search
set hlsearch
set ignorecase
set smartcase


" format file
nmap <leader>fef ggVG=

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" ================ Folds ============================

set foldmethod=indent   "fold based on indent
set foldnestmax=3       "deepest fold is 3 levels
set nofoldenable        "dont fold by default

" ================ Completion =======================

set wildmode=list:longest
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

" ================ Scrolling ========================

set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" == Keyboard Shortcuts ==

" quick ESC
imap jj <ESC>
imap kj <ESC>

" Make ";" act like ":"
nnoremap ; :

" Navigate windows easier
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
nnoremap <C-Left> :bp<CR>
nnoremap <C-Right> :bn<CR>
nnoremap <C-S-Left> :tabprevious<CR>
nnoremap <C-S-Right> :tabnext<CR>
nnoremap <D-[> :tabprevious<CR>
nnoremap <D-]> :tabnext<CR>
nnoremap <leader>yr :YRShow<CR>
nnoremap <leader>wc :bp<bar>sp<bar>bn<bar>bd<CR>

" curly brackets, create closing ones, new line, move to input stuff
inoremap {<CR> {<CR>}<Esc>O
"inoremap {<CR> {<CR>}<Esc>0<TAB>

" NERDTree
nmap <leader>n :NERDTreeTabsToggle<CR>

" Gundo
nmap ,u :GundoToggle<CR>

" == Plugin Stuff ==

let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
set laststatus=2

" Gundo settings
let g:gundo_right = 1

" a little wider for wider screens
let g:gundo_width = 60

" Make nerdtree look nice
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let g:NERDTreeWinSize = 30

let g:LustyJugglerSuppressRubyWarning = 1
let g:LustyJugglerAltTabMode = 1
let g:LustyJugglerShowKeys = 'a' " show a/s/d/f keys
