-- Home landing screen — mini.starter (part of mini.nvim, already installed; no new deps).
-- Shows recent files + quick actions when nvim opens with no file.
local starter = require 'mini.starter'

starter.setup {
  -- Run an item as soon as its prefix is unambiguous (e.g. press `f` to find file).
  evaluate_single = true,
  -- Banner generated by my own shout.sh (tiny font): `curl shout.sh/tiny/rlew.io`
  header = [[
█▀█ █   █▀▀ █ █ █   █ █▀█
█▀▄ █▄▄ ██▄ ▀▄▀▄▀ ▄ █ █▄█]],
  items = {
    starter.sections.recent_files(5, false),
    { section = 'Actions', name = 'Find file', action = 'Telescope find_files' },
    { section = 'Actions', name = 'Live grep', action = 'Telescope live_grep' },
    { section = 'Actions', name = 'File tree', action = 'Neotree toggle' },
    { section = 'Actions', name = 'New file', action = 'enew' },
    { section = 'Actions', name = 'Config', action = 'edit ' .. vim.fn.stdpath 'config' .. '/init.lua' },
    { section = 'Actions', name = 'Quit', action = 'qall' },
  },
  content_hooks = {
    starter.gen_hook.adding_bullet(),
    starter.gen_hook.aligning('center', 'center'),
  },
  footer = function()
    local ok, plugins = pcall(vim.pack.get)
    local n = ok and #plugins or 0
    local v = vim.version()
    return ('%d plugins · nvim v%d.%d.%d'):format(n, v.major, v.minor, v.patch)
  end,
}

-- vim: ts=2 sts=2 sw=2 et
