theme = "vesper"

[keys.normal]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"0" = "goto_line_start"

[keys.select]
"^" = "goto_first_nonwhitespace"
"$" = "goto_line_end"
"0" = "goto_line_start"
